# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Junyong's Blog
email: junyong@example.com
description: >
  This is my personal blog powered by Jekyll and hosted on GitHub Pages.
baseurl: ""  # 빈 값이면 루트에 배포
url: "https://zunyong01.github.io"
twitter_username: Taffyer
github_username: zunyong01

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Theme 설정 (중요!)
remote_theme: wild-flame/jekyll-simple
plugins:
  - jekyll-remote-theme

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
